#+title: All Post
#+hugo_base_dir: ../
#+hugo_section: posts

* DONE Stoffel :fauna:@curiosidades:
:PROPERTIES:
:EXPORT_FILE_NAME: stoffel
:END:
** ¿Un tejón melero?
Este genial mamífero carnívoro es nativo de África Subsahariana, Oriente Medio e India.

Con su longitud de hasta un metro y peso máximo de 20kg es conocido cómo el animal *más valiente del mundo*.

Considerado por la revista [[https://www.scientificamerican.com/][Scientific Americano]]; gramo a gramo el mamífero terrestre más temible de la tierra.
Tiene muy pocos depredadores y entres sus victimas se encuentran; /hienas, leones, tigres, erizos, cocodrilos.../ y no repara en atacar humanos si se siente amenazado. Una de sus comidas favoritas son las serpientes debido a una asombrosa *inmunidad al veneno*.

*** Inteligencia
Con un cerebro grande en proporción a su cuerpo y la capacidad de utilizar herramientas y la habilidad de resolver problemas complejos lo vuelven en uno de los mamíferos no-primate *más inteligente del planeta*. ([[yt:aZyjKF31_JQ][PBS]])

** Houdini de Moholoholo
Stoffel fue criado por un agricultor de la zona donde causo un caos. Fue llevado al [[https://www.facebook.com/moholorehabcentre][centro de vida salvaje y rehabilitación de Moholoholo]] en 1996 a la edad de un año y medio. Le fue entregado al fundador de Moholoholo Brian Jones quien rápidamente se encariño con el tejón.

Se le permitió andar libremente junto a dos hembras de tejón melero. Las hembras eventualmente volvieron a la vida salvaje, pero Stoffel se quedo en cautiverio debido a que había convivido con humanos desde una muy temprana edad y se creía que no sería capaz de adaptarse a la vida salvaje.

*** Primeros pasos
Causo estragos en el centro de rehabilitación, matando pequeños ciervos, conejos e incluso una águila leonada adulta.

También visitó el albergue donde echo al personal de la cocina, haciéndose con el control de esta mientras se servia un gran banquete.

En otra ocasión visito las habitaciones de los huéspedes, donde esculco entre las pertenencias en busca de algo que le interesara.

*** Escapes
Eventualmente fue colocado en un campamento con arboles y césped natural. De donde se escapo para *pelear con los leones*, terminando en la clínica por dos meses. Fue llevado de vuelta a su territorio donde inmediatamente intento escaparse para volver a pelearse con los leones.

Al final, con el apoyo del Club Rotario se le construyeron muros de ladrillo. Sin embargo después de solo unas horas en su nueva casa, se volvió a escapar /a pesar de las diferentes medidas que tomo el equipo para prevenir su escape/.
